n1 = int(input('Manda um numero ai pra nois: '))
n2 = int(input('Manda outro numero ai pra nois: '))
x=(n1+n2)
x1=(n1-n2)
x2=(n1*n2)
x3=(n1/n2)
x4=(n1**n2)
x5=(n1//n2)
x6=(n1%n2)
print(f'A soma do numero {n1} com o numero {n2} é igual a {x}')
print(f'A subtração do numero {n1} com o numero {n2} é igual a {x1}')
print(f'O produto do numero {n1} com o numero {n2} é igual a {x2}')
print(f'A divisão do numero {n1} com o numero {n2} é igual a {x3}')
print(f'A potenciação do numero {n1} com o numero {n2} é igual a {x4}')
print(f'A divisão inteira do numero {n1} com o numero {n2} é igual a {x5}')
print(f'O resto da divisão do numero {n1} com o numero {n2} é igual a {x6}')
